- name: Hello Wprld
  hosts: web
  tasks:
  - name: print hello world
    ansible.builtin.debug:
      msg: "Hello World!"

- name: PLAY-2
  hosts: local
  connection: local
  tasks:
  - name: play-2 and task-1
    ansible.builtin.debug:
      msg: "Hello from PLAY-2 and TASK-1"      