- name: demo on loops
  hosts: local
  connection: local
  tasks:
  - name: print names
    asnsible.builtin.debug:
      msg: "Hello {{ item }}" # iteam is reserved keyword
    loop: 
    - Vishwa
    - Chinta
    - Manofmasses
